package com.bobo.zktest.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Stock {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock.id
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock.name
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock.symbol
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	private String symbol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock.date
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock.price
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	private BigDecimal price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock.market
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	private String market;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock.createdon
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	private Date createdon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock.modifiedon
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	private Date modifiedon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stock.status
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock.id
	 * @return  the value of stock.id
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock.id
	 * @param id  the value for stock.id
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock.name
	 * @return  the value of stock.name
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock.name
	 * @param name  the value for stock.name
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock.symbol
	 * @return  the value of stock.symbol
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public String getSymbol() {
		return symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock.symbol
	 * @param symbol  the value for stock.symbol
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock.date
	 * @return  the value of stock.date
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock.date
	 * @param date  the value for stock.date
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock.price
	 * @return  the value of stock.price
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock.price
	 * @param price  the value for stock.price
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock.market
	 * @return  the value of stock.market
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public String getMarket() {
		return market;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock.market
	 * @param market  the value for stock.market
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public void setMarket(String market) {
		this.market = market;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock.createdon
	 * @return  the value of stock.createdon
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public Date getCreatedon() {
		return createdon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock.createdon
	 * @param createdon  the value for stock.createdon
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock.modifiedon
	 * @return  the value of stock.modifiedon
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public Date getModifiedon() {
		return modifiedon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock.modifiedon
	 * @param modifiedon  the value for stock.modifiedon
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public void setModifiedon(Date modifiedon) {
		this.modifiedon = modifiedon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stock.status
	 * @return  the value of stock.status
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stock.status
	 * @param status  the value for stock.status
	 * @mbg.generated  Tue Dec 24 14:16:56 CST 2019
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}