echo %1 %2 %3
rem echo need 3 params , params[1]=task folder, paras[2]=enable/disable, params[3]=prefix[dev2,qa,stage]
rem echo please make sure you provide 2 params;
rem pause
schtasks /change /%2 /TN "%1\%3 auto send email"
schtasks /change /%2 /TN "%1\%3 BOC Application File"
schtasks /change /%2 /TN "%1\%3 Cash Deposit Matching"
schtasks /change /%2 /TN "%1\%3 Clone Cash Product"
schtasks /change /%2 /TN "%1\%3 Clone FX Rate"
schtasks /change /%2 /TN "%1\%3 Close Cash Order"
schtasks /change /%2 /TN "%1\%3 ESOP Import"
schtasks /change /%2 /TN "%1\%3 FNZ Export"
schtasks /change /%2 /TN "%1\%3 FNZ Import"
schtasks /change /%2 /TN "%1\%3 FX Group"
schtasks /change /%2 /TN "%1\%3 Group Cash Order"
schtasks /change /%2 /TN "%1\%3 Import BOC Statement"
schtasks /change /%2 /TN "%1\%3 Import BOC subaccount Result"
schtasks /change /%2 /TN "%1\%3 Import HS Cashmovement"
schtasks /change /%2 /TN "%1\%3 Import HS Transaction Inquiry"
schtasks /change /%2 /TN "%1\%3 New Invitation Code Sync Process"
schtasks /change /%2 /TN "%1\%3 Push BOC Account to UC"
schtasks /change /%2 /TN "%1\%3 Push Trading status 2 PASS"
schtasks /change /%2 /TN "%1\%3 Sync All TO ROSS"
schtasks /change /%2 /TN "%1\%3 Sync CRS"
schtasks /change /%2 /TN "%1\%3 Sync Customer"
schtasks /change /%2 /TN "%1\%3 Sync Customer Role"
schtasks /change /%2 /TN "%1\%3 Sync NZ App 2 HK"
schtasks /change /%2 /TN "%1\%3 Sync Pending Cash Order"
schtasks /change /%2 /TN "%1\%3 Sync User"
schtasks /change /%2 /TN "%1\%3 Sync W8"
schtasks /change /%2 /TN "%1\%3 TestOnly Clear Boc Account File"